# EXAMPLE CONFIG FILE

mode: gui # REQUIRED: Options: gui or console

should_uncheck_filter: true # OPTIONAL (default=false): Find checkbox filter and uncheck all checkboxes before scraping
max_rows: null # OPTIONAL (default=None): Set a maximum number of rows to scrape (e.g. for reducing scraping time during testing)

console:
    url: https://app.powerbi.com/XXXXX # REQUIRED: URL to the Power BI report that should be scraped
    is_headless: true # OPTIONAL (default=true): 'true' hides the the browser window during scraping
    output_format: excel # OPTIONAL (default=excel): Options: excel, csv
    output_path: ./table.xlsx # OPTIONAL (default="./table.xlsx"): File extension should match the output_format (i.e. .xlsx for excel and .csv for csv)

gui:
    language: en # OPTIONAL (defaul=en): Options: en, da
    program_name: Power BI Table Scraper # OPTIONAL (defaul=Power BI Table Scraper) The program name that should be displayed in the GUI

    # Default values in the GUI. Can be changed by the user.
    default_values:
        url: https://app.powerbi.com/XXXXX # OPTIONAL (default=None): URL to the Power BI report that should be scraped
        is_headless: true # OPTIONAL (default=true): 'true' hides the the browser window during scraping
        output_format: excel # OPTIONAL (default=excel): excel or csv
        output_path: null # OPTIONAL(default=None): User is always required to browse for a valid path before being able to run the scraper unless a default path is specified here. File extension should match the output_format (i.e. .xlsx for excel and .csv for csv)
